docs:
- changed-files:
  - any-glob-to-any-file: ['**/*.md']
  
repo-update:
- changed-files:
  - any-glob-to-any-file: ['.github/**', '**/*.yml']
    
feature:
 - head-branch: ['^feature', 'feature']

fix:
 - head-branch: ['^fix', 'fix']